#!/bin/bash

# ==============================
# 📝 Create a New Item  Folder
# ==============================

#### STEP 1: prompt user input for the type of item to create ####

# 1 = blog, 2 = project, 3 = resource, 4 = knowledge_base (unit)
# user can enter the type of item they want to create
read -p "📰 Enter content type you want to add [1 = blog, 2 = project, 3 = resource, 4 = knowledge_base (unit)]: " content_type

#step 2: check if the input is valid input should be 1, 2, 3, or 4
if [[ ! "$content_type" =~ ^[1-4]$ ]]; then
  echo "❌ Invalid input. Please enter a number between 1 to add a blog, 2 to add a project, 3 to add a resource and 4 to add a unit under knowledge base."
  exit 1
fi

# Convert item type to string
case $content_type in
  1)
    content_type="blog"
    ;;
  2)
    content_type="project"
    ;;
  3)
    content_type="resource"
    ;;
  4)
    content_type="knowledge_base"
    ;;
esac


####  STEP 2: Mapping content type to content_destination
case $content_type in
  blog)
    content_destination="blogs"
    ;;
  project)
    content_destination="projects"
    ;;
  resource)
    content_destination="resources"
    ;;
  knowledge_base)
    content_destination="knowledge_base"
    ;;
esac

#### STEP 3: prompt user input for the title of the content to create
read -p "📝 Enter the title of the $content_type: " content_title


#### STEP 4: check if the title is valid no blank, no special characters,
if [[ -z "$content_title" ]]; then
  echo "❌ Title cannot be empty. Please enter a valid title."
  exit 1
fi
# Check for special characters  
if [[ "$content_title" =~ [^a-zA-Z0-9\ ] ]]; then
  echo "❌ Title contains special characters. Please enter a valid title."
  exit 1
fi

#step 4: create slug from the title
        # title is trimmed to single space, no leading or trailing spaces
        # and converted to slug
        # and item doesnt already exist by checking /content_destination/slug
# remove leading or trailing spaces from the title
content_title=$(echo "$content_title" | xargs)
# Convert multiple spaces to a single space 
content_title=$(echo "$content_title" | tr -s ' ')

#create slug from the title
slug=$(echo "$content_title" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')

### STEP 5:  Check if the slug already exists in the destination directory
            #  if slug already exists, exit with an error message
            # if slug doesnt exist, create the directory
if [ -d "$content_destination/$slug" ]; then
  echo "❌ $content_type '$content_title' already exists."
  exit 1
fi
# Create the directory
mkdir -p "$content_destination/$slug"

#### STEP 6: copy the template to the new content folder created above and add the main.yaml file

template_dir="assets/templates/$content_type-template"
# only the content inside the template folder is copied to the new content folder
cp -r "$template_dir/"* "$content_destination/$slug/"

#copy the main.yaml file to the new content folder and rename it to content_type.yaml
# the main.yaml file is copied from the assets/templates folder and renamed to content_type.yaml
cp "assets/templates/main.yaml" "$content_destination/$slug/$content_type.yaml"


#STEP 7 : create the content autogenerated metadata and standard content properties
author=$(git config user.name) # Get the author name from git config
created_timestamp=$(date "+%Y-%m-%d %H:%M:%S") # Get the current timestamp
created_date=$(date "+%Y-%m-%d") # Get the current date
last_updated_timestamp=$(date "+%Y-%m-%d %H:%M:%S") # Get the current timestamp
last_updated_date=$(date "+%Y-%m-%d") # Get the current date

# generate a unique id for the content using {content_type}_{slug initials}_{timestamp with no spaces}_author
content_id=$(echo "$content_type"_"${slug:0:3}"_"$(date +%s)"_"$author" | tr -d '[:space:]' | tr -d '[:punct:]')

# update the created content_type .yaml file with the autogenerated metadata
# replace the content_type.yaml properties with the autogenerated metadata above
# replace the content_type.yaml properties with the autogenerated metadata above
yaml_path="$content_destination/$slug/$content_type.yaml"

sed -i "s|content_title: .*|content_title: \"$content_title\"|" "$yaml_path"
sed -i "s|slug: .*|slug: \"$slug\"|" "$yaml_path"
sed -i "s|content_type: .*|content_type: \"$content_type\"|" "$yaml_path"
sed -i "s|content_destination: .*|content_destination: \"$content_destination\"|" "$yaml_path"
sed -i "s|content_id: .*|content_id: \"$content_id\"|" "$yaml_path"
sed -i "s|author: .*|author: \"$author\"|" "$yaml_path"
sed -i "s|created_timestamp: .*|created_timestamp: \"$created_timestamp\"|" "$yaml_path"
sed -i "s|created_date: .*|created_date: \"$created_date\"|" "$yaml_path"
sed -i "s|last_updated_timestamp: .*|last_updated_timestamp: \"$last_updated_timestamp\"|" "$yaml_path"
sed -i "s|last_updated_date: .*|last_updated_date: \"$last_updated_date\"|" "$yaml_path"


####### Set standard content properties

# replacing the content_source with the location of the Quarto output HTML location
content_source="$content_destination/$slug/content/index.html"
sed -i "s|content_source: .*|content_source: \"$content_source\"|" "$yaml_path"

# replace content_page with the location of the final content page
content_page="$content_destination/$slug/index.html"
sed -i "s|content_page: .*|content_page: \"$content_page\"|" "$yaml_path"

# update content imgages and assets path
thumbnail="$content_destination/$slug/images/thumbnail.png"
sed -i "s|thumbnail: .*|thumbnail: \"$thumbnail\"|" "$yaml_path"

hover_gif="$content_destination/$slug/images/thumbnail.gif"
sed -i "s|hover_gif: .*|hover_gif: \"$hover_gif\"|" "$yaml_path"

banner="$content_destination/$slug/images/banner.png"
sed -i "s|banner: .*|banner: \"$banner\"|" "$yaml_path"

#replace the gallery with a list of images located using the content_destination and slug
#Append the correct list to the end of the file
echo -e "gallery:\n  - \"$content_destination/$slug/images/image_1.png\"\n  - \"$content_destination/$slug/images/image_2.png\"\n  - \"$content_destination/$slug/images/image_3.png\"" >> "$yaml_path"




####  Build techstack_icons block
# Extract techstack values cleanly
techs=$(awk '
  /^techstack:/ {flag=1; next}
  flag && /^[^[:space:]]/ {flag=0}
  flag && /^[[:space:]]*-[[:space:]]*/ {
    sub(/^[[:space:]]*-[[:space:]]*/, "", $0)
    print
  }
' "$yaml_path")

# Create the icon list
techstack_icons="techstack_icons:"
while read -r tech; do
  techstack_icons+="\n  - /assets/images/${tech}.svg"
done <<< "$techs"

# Remove any existing icon block
sed -i '/^techstack_icons:/,/^ *- /d' "$yaml_path"

# Append the new block
echo -e "$techstack_icons" >> "$yaml_path"


#### STEP 8: when this script is run, the status of the content is set to draft
# replace content_status with draft
sed -i "s|status: .*|status: \"draft\"|" "$yaml_path"


# Message to show the user the content created
echo "🎉 $content_type '$content_title' created successfully!"
echo "📁 Location: $content_destination/$slug"
echo "🛠️  Edit the content at: $content_destination/$slug/quarto/index.qmd"
echo "📄 Your content will render to: $content_destination/$slug/content/index.html"



# 🔄 generating the content_type.json from content_type.yaml in the $content_destination/$slug"
echo "✅ Creating $content_type.json from $content_type.yaml..."

#the yaml file is defined above
# define the path to the json file
json_file="$content_destination/$slug/$content_type.json"
# check if the yaml file exists
if [ ! -f "$yaml_path" ]; then
  echo "❌ $yaml_path does not exist."
  exit 1
fi

# STEP 9: convert the yaml file to json file using python
python -c "import yaml, json, sys; json.dump(yaml.safe_load(open('$yaml_path')), open('$json_file', 'w'), indent=4)" 2>/dev/null
echo "✅ $content_type.json created successfully!"


#STEP 10: Regenerate the $content_destination summary yaml file
python scripts/regenerate_content_summary.py $content_type

# Final message to show the user the next steps
echo "📝 Edit the content at: $content_destination/$slug/quarto/index.qmd"


