project:
  type: website
  title: "My Portfolio Website"
  output-dir: ../

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2

website:
  navbar:
    left:
      - text: "Home"
        href: index
      - text: "Projects"
        menu:
          - text: "Project 1"
            href: projects/project1.html
          - text: "Project 2"
            href: projects/project2.html
          - text: "Sample Page"
            href: ../test_site/test.html
