
---
title: "Welcome to My Website"
format: html
---

# Welcome to My Website

Hello! I'm [Your Name], and this is my professional portfolio and blog. Here you can find details about my projects, read my blog posts, and learn more about my professional journey.

## Portfolio
Explore my portfolio to see a range of projects I've worked on covering various aspects of data engineering, data visualization, and more. 
[View Portfolio](content/portfolio/portfolio.html)

## Blog
Check out my blog for articles on topics in data science, personal development, and industry insights.
[Read Blog](content/blog/blog.html)

## Projects
Dive deeper into some of my major projects that showcase my capabilities in building complex systems and innovative solutions.
[View Projects](content/projects/projects.html)

## Resume
Learn more about my professional background and download my resume.
[View Resume](content/resume/resume.qmd)

## Connect with Me
Feel free to connect with me on [LinkedIn](https://www.linkedin.com/in/sandra-alemayehu/), [GitHub](https://github.com/san-dra), or watch my tutorials on [YouTube](https://youtube.com/user/yourchannel).

